FROM node:16-alpine3.11 as dependencies
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

FROM node:16-alpine3.11 as builder
WORKDIR /app
COPY . .
RUN rm -rf ./data
RUN rm -rf ./public/assets/pages
COPY --from=dependencies /app/node_modules ./node_modules
