version: '3.4'

services:
  postgres:
    image: postgres:12.2
    environment:
      POSTGRES_DB: contentium
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
    - dbdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:4.18
    ports:
      - 8085:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@contentium.io
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    volumes:
    - pgadmindata:/var/lib/pgadmin
    links:
    - postgres:pgsql-server

  contentium:
    image: contentium/server
    restart: unless-stopped
    ports:
      - 8000:80
    environment:
      PORT: 80
      NODE_ENV: Docker
      ADMIN_EMAIL: "root@content.io"
      ADMIN_PASSWORD: "password"
    build:
      context: ..
      dockerfile: ./server/Dockerfile

volumes:
  dbdata:
  pgadmindata: